In [2]:
from tensorflow.keras.layers import TextVectorization
import tensorflow as tf

In [3]:
texts = [
    "Hello, how are you?",
    "I am doing well, thank you!",
    "How about you?",
    "I am also doing great!"
]

In [4]:
vectorizer = TextVectorization(output_mode='int', 
                               max_tokens=100,
                               output_sequence_length=10)

In [6]:
vectorizer.adapt(texts)
text_vectorized = vectorizer(texts)
print("Vectorized text:\n", text_vectorized.numpy())

Vectorized text:
 [[ 9  4 11  2  0  0  0  0  0  0]
 [ 3  6  5  7  8  2  0  0  0  0]
 [ 4 13  2  0  0  0  0  0  0  0]
 [ 3  6 12  5 10  0  0  0  0  0]]
